GET http://localhost:1024/ebook/list?name=Spring
Accept: application/json

### gtr

GET http://localhost:1024/ebook/list
Accept: application/json

### gtr

GET http://localhost:1024/ebook/list?page=1&size=4
Accept: application/json

### gtrp
